### ISSUE TITLE
Could not find the game

### ISSUE THREAD

**Issue by be90728** [Pupix/lol-client-api-explorer#2]
An error occurred: Could not find the game
I'm sure my game is open !!! My area Garena-Tw

**Comment by be90728** [comment]
===> Couldn\'t find league process

**Comment by Pupix** [comment]
Hi!

Does Garena have the new LCU client? This was made with that in mind.

**Comment by be90728** [comment]
Yes , you can test

**Comment by be90728** [comment]
My operating system is windows 10, have used windows7 tested, or the same can not be used.

**Comment by Pupix** [comment]
can you take a screen shot of your process list? What's the name of the LCU executable?

**Comment by be90728** [comment]
https://imgur.com/a/mJdM7

If you have Skype or Discord, our processing efficiency will be faster

**Comment by be90728** [comment]
https://discord.gg/Ze39bh

**Comment by Pupix** [comment]
solved via discord
